### ISSUE TITLE
Windows下面没办法直接在vscode的终端中运行

### ISSUE THREAD

**Issue by tabris-trees** [shinyypig/matlab-in-vscode#1]
它会先打开matlab的命令行， 所以执行不了文件中的命令
![Code_U4x6w7xE4g](https://user-images.githubusercontent.com/39879580/227839837-cd001ec7-0d5e-448d-aa6a-43b228a58602.gif)

我看网上提供的解决方案需要用python调用命令行的interface
[https://www.jianshu.com/p/01d5f4c38ac3](https://www.jianshu.com/p/01d5f4c38ac3)

希望能够解决这个问题（不知道是不是只有我自己有这个问题😂）

**Comment by shinyypig** [comment]
在windows上测试了一下，才发现matlab在windows和macos还有linux不一样。在后两者中，执行`matlab -nodesktop -nosplash`是直接在terminal里面打开matlab的命令行的。但是windows中会仍然打开gui。

更新了一下程序，在新版里面新增了一个配置项`matlabCMD`,你可以将其设置为

<img width="476" alt="image" src="https://user-images.githubusercontent.com/30233673/227846520-3d3e9558-d81c-4698-b078-7649906c5385.png">

应该就可以正常运行代码了，但是无法运行plot之类涉及到gui的函数。

后续有时间了，我再看看windows下到底应该怎么配置吧。

**Comment by tabris-trees** [comment]
> 在windows上测试了一下，才发现matlab在windows和macos还有linux不一样。在后两者中，执行`matlab -nodesktop -nosplash`是直接在terminal里面打开matlab的命令行的，但是windows中会仍然打开gui。
> 
> 更新了一下程序，在新版里面新增了一个配置项`matlabCMD`,你可以将其设置为
> 
> <img width="476" alt="image" src="https://user-images.githubusercontent.com/30233673/227846520-3d3e9558-d81c-4698-b078-7649906c5385.png">
> 
> 应该就可以正常运行代码了，但是无法运行plot之类涉及到gui的函数。
> 
> 后续有时间了，我再看看windows下到底应该怎么配置吧。
> 

好的，非常感谢！

**Comment by shinyypig** [comment]
0.2.1 更新中新增了 matlab engine for python 支持，可以在windows下使用GUI方面的函数了。但是需要额外配置python环境。
