### ISSUE TITLE
Windows下无法正常使用

### ISSUE THREAD

**Issue by EnjoyXu** [shinyypig/matlab-in-vscode#11]
首先如果不用python backend那么， matlab -nodesktop -nosplash这行命令还是会弹出command line界面。然后就运行不下去了。

如果使用python backend，程序还是可以运行的，但是无法查看变量。在终端里看到输入了variable_info，但是这行命令是无效的。

**Comment by shinyypig** [comment]
windows 下 matlab 终端和 linux 以及 macOS 中的不一样，推荐使用python backend。

至于第二个问题，是默认的`matlab-in-vscode.matlabStartup`问题。因为我自己的这个配置早就修改了，所以一直没有发现这个bug。我在新版本 0.4.4 中已经修复了，你可以等待更新，或者手动修改`matlab-in-vscode.matlabStartup`这一配置。

非常感谢！

**Comment by EnjoyXu** [comment]
我不是很清楚怎样修改这个配置来解决这个问题:(

如果方便的话，能将这个配置发一份，让我模仿地改一改吗？
如果不方便的话，希望能快点更新版本:)

感谢

**Comment by shinyypig** [comment]
<img width="360" alt="image" src="https://github.com/shinyypig/matlab-in-vscode/assets/30233673/3032a132-c5bf-4c1a-b1d9-f8c5d3cd1950">

点击`Edit in settings.json`，下方是一个示例，每一行都代表了一个你希望在Terminal启动时运行的代码。 

```json
"matlab-in-vscode.matlabStartup": [
      "set(groot, 'defaultLineLineWidth', 2);",
      "set(groot, 'DefaultLineMarkerSize', 8);",
      "set(groot, 'defaultAxesFontSize', 18);",
      "set(groot, 'defaultAxesXGrid', 'on');",
      "set(groot, 'defaultAxesYGrid', 'on');",
      "set(groot, 'defaultAxesBox', 'on');",
      "set(groot, 'defaultLegendBox', 'off');",
  ],
```

当然，你也可以直接更新，最新版已经可以下载了。

**Comment by EnjoyXu** [comment]
我不确定是不是我没设置好的原因，我尝试把这个参数设置成上面的，或者ReadMe里所展示的。而且我已经升级插件到了v0.4.4但是问题还是没有解决:(

```
"matlab-in-vscode.matlabStartup": [
        "addpath(genpath('./'));",
        "set(groot, 'defaultLineLineWidth', 2);",
        "set(groot, 'DefaultLineMarkerSize', 8);",
        "set(groot, 'defaultAxesFontSize', 18);",
        "set(groot, 'defaultAxesXGrid', 'on');",
        "set(groot, 'defaultAxesYGrid', 'on');",
        "set(groot, 'defaultAxesBox', 'on');",
        "set(groot, 'defaultLegendBox', 'off');",
        "format compact;"
    ]

```

终端上还是显示这个样子，没有改变。

```
>>> variable_info;
 eval
 'variable_info'
```

是我哪里做错了吗？请指教

**Comment by shinyypig** [comment]
<img width="2099" alt="image" src="https://github.com/shinyypig/matlab-in-vscode/assets/30233673/6c1a9fae-fc09-418b-a7c8-fc9ca0c79fbb">
把刚启动时的终端截图发一下，variable_info 就是我写的一个.m函数，

`addpath('/Users/liangliang/.vscode/extensions/shinyypig.matlab-in-vscode-0.4.4/matlab_code/');`

这一行代码就是用来添加路径的。

**Comment by EnjoyXu** [comment]
![image](https://github.com/shinyypig/matlab-in-vscode/assets/62149347/6e4dc863-a5cb-4f71-97c4-cf4506f8d808)

在我点击`Run Current Matlab File`按钮以后终端里就显示这样。看上去好像并没有执行startUp里面的语句。

**Comment by shinyypig** [comment]
没有遇到过这种情况。

会不会是`matlab-in-vscode.matlabStartup`被重复设置了？你在`settings.json`搜索一下试试？

**Comment by EnjoyXu** [comment]
似乎并不是:(
这个设置是唯一的。请问还有其他的可能吗？

**Comment by shinyypig** [comment]
我更改了输入启动命令的方式，你升级到0.4.5版本试试。

**Comment by EnjoyXu** [comment]
![image](https://github.com/shinyypig/matlab-in-vscode/assets/62149347/679e96d6-274b-49dc-a1e1-bbc7ab6d6abe)

启动时运行语句的问题解决了，运行`varaible_info`可以正常运行，但是vscode里面无法正常显示。

![image](https://github.com/shinyypig/matlab-in-vscode/assets/62149347/5144a1b9-50ca-4022-a80c-f2b39b7d3919)

我查看了生成的`.csv`文件，是正常的，但是vscode这边好像没有加载了。

**Comment by shinyypig** [comment]
删掉csv文件再试试。

**Comment by EnjoyXu** [comment]
好像没有用

**Comment by shinyypig** [comment]
这就不清楚了，我在我的Windows电脑上测试了一下，没有问题。

p.s. 不需要手动运行 `variable_info`，点击小眼睛的图标就能显示变量。

**Comment by WilliamZh99** [comment]
我已经安装MATLAB Engine，仍然无法在终端里运行

```
PS C:\Users\Willi> matlab -nodesktop -nosplash
PS C:\Users\Willi> disp(['Working directory: ', pwd]);addpath('c:\Users\Willi\.vscode\extensions\shinyypig.matlab-in-vscode-0.4.5\matlab_code\');
所在位置 行:1 字符: 7
+ disp(['Working directory: ', pwd]);addpath('c:\Users\Willi\.vscode\ex ...
+       ~
"[" 后面缺少类型名称。
所在位置 行:1 字符: 28
+ disp(['Working directory: ', pwd]);addpath('c:\Users\Willi\.vscode\ex ...
+                            ~
参数列表中缺少参量。
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingTypename
```

**Comment by WilliamZh99** [comment]
> ![image](https://user-images.githubusercontent.com/62149347/253864282-679e96d6-274b-49dc-a1e1-bbc7ab6d6abe.png)
> 
> 启动时运行语句的问题解决了，运行`varaible_info`可以正常运行，但是vscode里面无法正常显示。
> 
> ![image](https://user-images.githubusercontent.com/62149347/253867041-5144a1b9-50ca-4022-a80c-f2b39b7d3919.png)
> 
> 我查看了生成的`.csv`文件，是正常的，但是vscode这边好像没有加载了。

我也遇到同样的问题
