### ISSUE TITLE
Error running on MacOS

### ISSUE THREAD

**Issue by aminsalehiapple** [shinyypig/matlab-in-vscode#13]
The extension does not work on MacOS with the following bash error:
bash: syntax error near unexpected token `['Working directory: ','

**Comment by shinyypig** [comment]
It seems that the matlab terminal did not start properly. Could you please try  running the following command and tell me the result?
```bash
matlab -nodesktop -nosplash    
```
Typically, the terminal should look like this:
<img width="852" alt="image" src="https://github.com/shinyypig/matlab-in-vscode/assets/30233673/044f4ca4-010e-402f-b531-704eebdba289">

**Comment by Fontanapink** [comment]
When I run that command I get a MATLAB Command Window pop up.

**Comment by shinyypig** [comment]
> When I run that command I get a MATLAB Command Window pop up.

If you cannot open matlab directly in a terminal, you may try the pybackend.
