### ISSUE TITLE
Bug 运行时fprintf无法输出中文

### ISSUE THREAD

**Issue by xpsakaubtth42019** [shinyypig/matlab-in-vscode#17]
![image](https://github.com/shinyypig/matlab-in-vscode/assets/122611550/d121a21a-7fcf-4d98-984e-835ca019cfc7)
运行时fprintf无法输出中文
同时，是否可以添加运行前保存的选项

**Comment by shinyypig** [comment]
在最新的预览版0.4.8中应该可以输出中文了，你试试看。

**Comment by xpsakaubtth42019** [comment]
wow！是的，解决了

**Comment by xpsakaubtth42019** [comment]
是否添加一个自动保存的选择会更好呢

**Comment by shinyypig** [comment]
在0.4.9中添加了这个功能。

**Comment by xpsakaubtth42019** [comment]
nice
