### ISSUE TITLE
Bug 版本更新后 文件夹名字变化 路径更改 查看变量功能消失

### ISSUE THREAD

**Issue by xpsakaubtth42019** [shinyypig/matlab-in-vscode#18]
版本更新后，从matlab中预设的文件夹名字会发生变化，路径更改，查看变量功能消失需要重新为variable_info.m设置路径，可能可以加到matlabStartup里面，动态跟随变化

**Comment by xpsakaubtth42019** [comment]
补充一下，试了一下好像不行
<img width="632" alt="image" src="https://github.com/shinyypig/matlab-in-vscode/assets/122611550/3f5e0406-38fb-4731-8d54-4f5d70bb3bcc">

**Comment by shinyypig** [comment]
路径都是自动生成的：

https://github.com/shinyypig/matlab-in-vscode/blob/12ea045df20838d933f68aafc81564ce34fcaeb5/src/extension.ts#L127C1-L130C23

我猜测可能是因为启动matlab的指令在终端一调用就发送过去了，这时终端还没有初始化完毕，导致部分指令没有成功运行。我现在在0.4.12中添加了一个延迟，不知道有没有解决这个问题。

**Comment by xpsakaubtth42019** [comment]
> 

貌似没有解决，目前是直接将variable_info.m脚本单独提取出来放在所添加的默认路径下使用

**Comment by shinyypig** [comment]
<img width="922" alt="image" src="https://github.com/shinyypig/matlab-in-vscode/assets/30233673/026439c5-df1d-48c4-93bf-abf045db8bb4">
给一个调出matlab终端命令的截图，类似于上图。

**Comment by shinyypig** [comment]
我在我的windows pc上测试了一下，没有问题。

看你的截图，输入的命令也是对的。

你直接在 CMD 或者 PowerShell 中输入 `python "c:\ ....` 这个命令，也不能成功添加路径吗？

**Comment by xpsakaubtth42019** [comment]
我删除了所有插件之后重新配置解决了，非常抱歉，看起来是由插件冲突导致的

> 我在我的windows pc上测试了一下，没有问题。
> 
> 看你的截图，输入的命令也是对的。
> 
> 你直接在 CMD 或者 PowerShell 中输入 `python "c:\ ....` 这个命令，也不能成功添加路径吗？
