### ISSUE TITLE
Enhancement 识别文件中的clc 清理终端历史

### ISSUE THREAD

**Issue by xpsakaubtth42019** [shinyypig/matlab-in-vscode#19]
是否根据实际文件中的clc，clear、close等，清理终端、历史

**Comment by shinyypig** [comment]
clc clear close 不都是能正常运行的吗？

**Comment by xpsakaubtth42019** [comment]
> 指令窗口单独可以运行，我的意思是文件中的clc是否可以反应到输出的终端里，将终端的上一个输出清除
![image](https://github.com/shinyypig/matlab-in-vscode/assets/122611550/f2a75dd2-bd56-4418-93d0-03bea7b64fb6)

**Comment by shinyypig** [comment]
这不是很好做，在pybackend中，clc 这个命令实际上是无效的。之所以现在能部分运行，是因为做了一个单独的识别，判断输入的指令是否为 clc。如果是运行某个文件，然后代码中包含了clc，那就需要对代码进行解析，判断是否有clc。这难免会引入bug。
