### ISSUE TITLE
Bug 运行时第一次是前一次的编辑运行结果，第二次才是新的编辑结果

### ISSUE THREAD

**Issue by Rain-Of-Stars** [shinyypig/matlab-in-vscode#20]
Bug 运行时第一次是前一次的编辑，第二次才是新的编辑结果，不知道是否和插件的自动保存逻辑相关

**Comment by shinyypig** [comment]
感谢指出问题，已在 v0.4.15 中修复。

**Comment by Rain-Of-Stars** [comment]
> 感谢指出问题，已在 v0.4.15 中修复。

您好，已经重新安装v0.4.15但仍旧需要运行两次才是新的结果

**Comment by Rain-Of-Stars** [comment]
> > 感谢指出问题，已在 v0.4.15 中修复。
> 
> 您好，已经重新安装v0.4.15但仍旧需要运行两次才是新的结果

采用的是Python环境下调用matlab的engine方法

**Comment by shinyypig** [comment]
发现一个很有意思的现象，你可以尝试一下如下操作：

1. 修改函数文件，比如叫 `test.m`
2. 手动保存该文件
3. 快速点击右上角的运行按钮

这样其实是确保了函数是在保存之后才运行的，但是运行结果仍旧是上个版本的结果。

不太清楚到底是什么问题，还在debug中。

**Comment by shinyypig** [comment]
经过验证，是python matlab engine 的问题，并且插件不使用 matlab pybackend 的时候，是正常工作的。

**Comment by zhangyux1** [comment]
请问这个问题解决了吗？我也遇到了类似的问题，而且运行很多次都是上一次编辑运行的结果，除非重启vscode。

**Comment by shinyypig** [comment]
是 python matlab engine 的问题，本插件无法修复这个问题。
