### ISSUE TITLE
windos上更改matlab cmd 后仍然无法运行

### ISSUE THREAD

**Issue by lyj76** [shinyypig/matlab-in-vscode#21]
<img width="394" alt="image" src="https://github.com/shinyypig/matlab-in-vscode/assets/116193305/ec4bb9bc-43b4-4828-bf97-8e5ef322384f">
<img width="791" alt="9f752fd582aa8780f265e4688e8e644" src="https://github.com/shinyypig/matlab-in-vscode/assets/116193305/0acb892e-1cd7-4fc0-97d5-3ed904add167">
一直显示这个错误（我同时已经安装了matlab的官方插件）

**Comment by shinyypig** [comment]
Windows请参考 readme 安装 python matlab engine，并且勾选pybakend。

nojvm似乎并不是总能起作用，稍后我会更新 readme。

**Comment by shinyypig** [comment]
readme 已更新
