### ISSUE TITLE
安装后运行code报错

### ISSUE THREAD

**Issue by Qihai-Weng** [shinyypig/matlab-in-vscode#23]
<img width="1294" alt="Screenshot 2023-09-27 at 3 08 04 PM" src="https://github.com/shinyypig/matlab-in-vscode/assets/71131478/be73b82a-2f17-47b7-b4e0-8c2d4fe800fc">

**Comment by Qihai-Weng** [comment]
操作系统为macos

**Comment by shinyypig** [comment]
这是因为你没有将matlab添加到路径，可以将 `matlabCMD` 更换为：

```
/Applications/MATLAB_R2023b.app/bin/matlab -nodesktop -nosplash
```

`/Applications/MATLAB_R2023b.app/bin`这部分的内容请根据自己实际的安装路径和版本进行修改。

**Comment by Qihai-Weng** [comment]
感谢！
