### ISSUE TITLE
Python path setting

### ISSUE THREAD

**Issue by oletf** [shinyypig/matlab-in-vscode#24]
Greetings,

The default command for python interpreter is calling `python` as [defined here](https://github.com/shinyypig/matlab-in-vscode/blob/9a06e1f6279246b526eb717082c20a3180dc3a90/src/extension.ts#L140).

I need to use a python interpreter which is not the default one which is called by `python`.

Would it be possible to add a setting like `matlab-in-vscode.matlabPythonCMD` which would be used instead of the default `python` keyword ?

Thanks forward

**Comment by shinyypig** [comment]
You can specify the path of python in v0.4.16.

Thanks for your constructive suggestion!

**Comment by oletf** [comment]
Awesome ! thanks for the quick response
(opening a separate issue for another problem, because unrelated)
