### ISSUE TITLE
Pybackend quotes in Windows

### ISSUE THREAD

**Issue by oletf** [shinyypig/matlab-in-vscode#25]
Hi,

[The triple double quotes here](https://github.com/shinyypig/matlab-in-vscode/blob/a7df4ff3080c679080627eb51cdb31e9c8f27538/src/extension.ts#L143C4-L143C4) seem to disturb windows cmd and the whole addpath for the `variable_info` function is never added (as well as the pwd). They might be escaped somehow.

```
C:\Users\user\project>py -3.5 "c:\Users\user\.vscode\extensions\shinyypig.matlab-in-vscode-0.4.16\pybackend\matlab_engine.py" --cmd="""disp(['Working directory: ', pwd]);addpath('c:\Users\user\.vscode\extensions\shinyypig.matlab-in-vscode-0.4.16\matlab_code\');"""
---------------------------------------------------------
MATLAB Engine for Python is ready (terminate with 'quit')
---------------------------------------------------------

ans =

    "disp(['Working directory: ', pwd]);addpath('c:\Users\user\.vscode\extensions\shinyypig.matlab-in-vscode-0.4.16\matlab_code\');"


>>> variable_info;

Error using eval
Undefined function or variable 'variable_info'.


>>>
```

I tried just replacing the triple by simple double quotes and it works perfectly, but I don't know if it'll break anything on Unix based shells.
```diff
-                    ` "${scriptPath}" --cmd="""${startupCommand}"""`;
+                    ` "${scriptPath}" --cmd="${startupCommand}"`;
```

**Comment by oletf** [comment]
also related enough, 
the [`runMatlabFile`](https://github.com/shinyypig/matlab-in-vscode/blob/a7df4ff3080c679080627eb51cdb31e9c8f27538/src/extension.ts#L223C49-L223C49) function doesn't work on my side because Matlab's [`run` function](https://uk.mathworks.com/help/matlab/ref/run.html?s_tid=doc_ta#btdr9t5-1-scriptname) in versions **prior to R2018** only takes a character vector as `scriptname` arg (and not a `string scalar | character vector`).

Since 2023 still accepts `character vector` for this native function, changing with 
```diff
-            let matlabCommand = `run("${relativePath}")`;
+            let matlabCommand = `run('${relativePath}')`;
```
shouldn't break anything in versions R2018 and after (confirmed it works on my side, but would need check on other versions just in case).

**Comment by shinyypig** [comment]
Thank you for your contribution! I have confirmed that it also works on macOS. The relevant code has been updated in version 0.4.17.

Once again, thank you for your assistance!
