### ISSUE TITLE
windows上插件的其他功能正常，但是查看变量区的功能无法使用

### ISSUE THREAD

**Issue by SJM946** [shinyypig/matlab-in-vscode#26]
![QQ截图20231024223844](https://github.com/shinyypig/matlab-in-vscode/assets/146961359/233e9c58-de2e-4319-9587-b323c321fa04)
csv文件能够生成，但是在vscode中却无法打开。
这个插件真的很有用，希望这个问题能够得到解决！

**Comment by shinyypig** [comment]
试一下删除生成的csv文件，在重新打开VSCode。

我也很困扰，不少人反映查看变量这个功能无法使用，但我这边的PC上没有问题，我都不知道那里出了问题。

ps. 你的vscode打开一个文件夹了吗，需要打开一个文件夹作为工作区，不然插件无法获取生成的csv文件路径？

**Comment by SJM946** [comment]
原来如此，我没有在vscode中打开文件夹。感谢你的帮助，打开变量区的功能真的非常有用，比其他matlab插件好多了，希望这个插件越做越好！

**Comment by 1466649452** [comment]
确实是这个原因，当vscode打开的文件夹中包含有多个子文件夹，对应的csv文件会在某个子文件夹（某次运行代码所在的文件夹）中，就找不到了。逻辑是否可以修正为寻找当前工作文件夹中的csv文件？
