### ISSUE TITLE
`runMatlabFile()` fails in multi root workspaces

### ISSUE THREAD

**Issue by cincofe** [shinyypig/matlab-in-vscode#28]
If the workspace contains an additional folder (on top of the main workspace folder), the relative path used as argument of the Matlab's `run()` instruction contains the name of the folder itself and execution fails.

Possibly related to [this issue](https://github.com/microsoft/vscode/issues/68929#issue-411523969) with `vscode.workspace.asRelativePath`?

## Successful execution example
In the folder `/path/to/sometoolbox`, the `sometoolbox` workspace is defined by `sometoolbox.code-workspace`, which contains the following:

```json
{
	"folders": [
		{
			"path": "."
		}
	],
	"settings": {}
}
```
When the ⏩ button is pushed while `somescript.m` is the current document, the add-on issues the following Matlab command, which is correct:
```matlab
run('somescript.m')
``` 

## Failed execution example
If the `/path/to/anothertoolbox` folder is added to the same workspace, the resulting `sometoolbox.code-workspace` is:
```json
{
	"folders": [
		{
			"path": "."
		},
		{
			"path": "../anothertoolbox"
		}
	],
	"settings": {}
}
```

Now, running the current document produces the following Matlab command:
```matlab
run('sometoolbox/somescript.m')
``` 
which is of course incorrect and produces the following error:
```
Error using cd
Unable to change current folder to '/path/to/sometoolbox/sometoolbox' (Name is nonexistent or not a folder).
Error in run (line 48)
    cd(fileDir); 
```

---

Tested with: 
> Name: Matlab in VSCode
Id: shinyypig.matlab-in-vscode
Description: Run Matlab code in VSCode
Version: 0.4.20
Publisher: shinyypig
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=shinyypig.matlab-in-vscode

on VS Code:
 > Version: 1.84.1
  Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
  Date: 2023-11-06T12:37:31.808Z
  Electron: 25.9.2
  ElectronBuildId: 24603566
  Chromium: 114.0.5735.289
  Node.js: 18.15.0
  V8: 11.4.183.29-electron.0
  OS: Darwin arm64 22.6.0

**Comment by shinyypig** [comment]
You need to ensure that the workspace path of matlab is the same as that of vscode.workspace, which is also the default setting. 

Sorry, I just cannot understand the problem. Do you mean that you want to run a file that is outside the workspace?

**Comment by cincofe** [comment]
In `/src/extension.ts` [line 222](https://github.com/shinyypig/matlab-in-vscode/blob/596e47577fe43e72a2ebd05564c694c99229101f/src/extension.ts#L222C55-L222C55):
```
let relativePath = vscode.workspace.asRelativePath(filePath);
```
`relativePath` has the correct value most of the time, *except* when the VS workspace ha multiple roots, i.e. when you added a second folder using _File > Add folder to workspace ..._.

The workaround is of course to remove the extra folder before running the code, but sometimes it comes handy to keep related files/folders open in the some workspace.
