### ISSUE TITLE
【BUG】异步导致保存问题

### ISSUE THREAD

**Issue by Rain-Of-Stars** [shinyypig/matlab-in-vscode#30]
有个思路，是否能用Python的os.path.getmtime()函数来获取文件的最后修改时间，并将其与MATLAB引擎的启动时间进行比较。如果文件在启动引擎后被修改，那么再执行相应的命令，解决运行保存问题

**Comment by shinyypig** [comment]
本插件目前是在文件保存后再运行对应的代码的，问题出在`MATLAB Engine API for Python`上。你可以单独测试这个python库，它内部似乎有缓存之类的机制。

https://github.com/shinyypig/matlab-in-vscode/assets/30233673/b236ee42-8b90-4241-9eed-c3c212a9cac6
