### ISSUE TITLE
Windows11 已安装MATLAB engine for python，已在设置中勾选 pybackend，已添加环境变量，仍无法正常运行

### ISSUE THREAD

**Issue by Gew404** [shinyypig/matlab-in-vscode#31]
![image](https://github.com/shinyypig/matlab-in-vscode/assets/93397828/f9c12e87-a3b4-4726-ac10-e166527e74c5)
如图，请问这是哪里出了问题呢？
settings.json配置如下图，python版本为3.8（之前装了3.12之后卸载了），python窗口内可以正常调用Matlab engine for python，之后使用了code runner插件也可正常调用。
![image](https://github.com/shinyypig/matlab-in-vscode/assets/93397828/649a4210-9069-409d-a2e1-03c65ef13b39)

**Comment by shinyypig** [comment]
没有配置 `"matlab-in-vscode.matlabPythonPath"`，你可以删除这一行，从而使用默认配置；或者指定你想要用的`python`路径，不能空着。

**Comment by Gew404** [comment]
我删除了那一行，重启了vscode之后运行，但还是之前的报错

**Comment by shinyypig** [comment]
<img width="765" alt="image" src="https://github.com/shinyypig/matlab-in-vscode/assets/30233673/cc556469-d752-4dce-9d7f-8f3221085f03">

重置这个选项试试。你现在这个报错说明 python 没有成功启动，你可以注意一下首次启动时终端中输入的指令。

**Comment by Gew404** [comment]
非常感谢！重置后已解决问题
