### ISSUE TITLE
在虚拟环境下安装matlab engineAPI后对应插件应该怎么设置？

### ISSUE THREAD

**Issue by Azl369** [shinyypig/matlab-in-vscode#33]
![image](https://github.com/shinyypig/matlab-in-vscode/assets/73180687/0ab461d5-df4e-4265-b8ad-550d9808e5da)
如上图matlab engineAPI已经在虚拟环境下面安装
![image](https://github.com/shinyypig/matlab-in-vscode/assets/73180687/d1fb319a-c9fb-41c2-baa6-623c420b6998)
使用默认设置时报错如上
![image](https://github.com/shinyypig/matlab-in-vscode/assets/73180687/057f1d87-994e-4cb1-9e70-655ee92904c0)
更改文件路径重启后，报错如下
![image](https://github.com/shinyypig/matlab-in-vscode/assets/73180687/63dc3998-419a-4dfa-9a1d-61f3ccda9cef)

**Comment by shinyypig** [comment]
这是因为你的python路径里面有空格，命令行是不能识别这样的路径的。我印象中，可以这样来输入带空格的路径
```
C:\Program/ Files\Polyspace\R2020b\extern\engines\python
```
或者用引号
```
"C:\Program Files\Polyspace\R2020b\extern\engines\python"
```
不一定对，你可以自己搜索一下，确保能在终端中输入你给定的字符串，能打开Python就应该没问题了。
