### ISSUE TITLE
Support to load local functions?

### ISSUE THREAD

**Issue by randolfly** [shinyypig/matlab-in-vscode#34]
Hello! Is it possible to support invoke of local functions? The scenerio is like this. It would be truely helpful to support local functions when writing codes.

![image](https://github.com/shinyypig/matlab-in-vscode/assets/37769048/dcc0f596-6e43-4f45-afa1-c1be332a9e8f)

BTW, this is a great plugin, and it really helps a lot. Thanks!

**Comment by shinyypig** [comment]
Running the entire .m file allows for the invocation of local functions. However, when it comes to executing a specific cell or line, I haven't yet discovered an elegant solution. Perhaps this functionality could be realized in the future.

Thank you for your valuable suggestion!

**Comment by randolfly** [comment]
ok, thanks for your reply!
