### ISSUE TITLE
doesn't work with matlab2023b and python3.11

### ISSUE THREAD

**Issue by LiquidTaeJa** [shinyypig/matlab-in-vscode#35]
Downloaded the plugin in vscode and followed the instructions to configure the matlab backend, but no buttons appear in vscode and the matlabengine does not start.

**Comment by LiquidTaeJa** [comment]
我补充一下，path添加到了环境变量并且matlabengine可以通过代码成功运行

![屏幕截图 2024-03-01 163206](https://github.com/shinyypig/matlab-in-vscode/assets/96654938/318b4f43-51e6-4096-999a-c3abf006f292)

插件也按照要求设置好了

![屏幕截图 2024-03-01 163337](https://github.com/shinyypig/matlab-in-vscode/assets/96654938/fd644cbf-c192-482b-a08a-1cc17afd5557)

但是vscode里没有任何反应

![屏幕截图 2024-03-01 163800](https://github.com/shinyypig/matlab-in-vscode/assets/96654938/ef524937-f29a-4931-a478-4ca25c27cf8a)

**Comment by shinyypig** [comment]
现在你的 matlab 代码被识别为了 c 语言代码，你可能需要先安装官方的 matlab 插件。

**Comment by LiquidTaeJa** [comment]
是这个问题，已解决，感谢作者回复，很好用的插件！
