### ISSUE TITLE
Need to run twice when using "Run current MATLAB file"

### ISSUE THREAD

**Issue by GYC-lab** [shinyypig/matlab-in-vscode#40]
I wonder if anyone has encountered this bug that if I make some modifications on my code and then click "Run current MATLAB file", it does not run the newest code and another run is needed.

Any help would be truly appreciated!

**Comment by shinyypig** [comment]
It is a bug related to `python matlab engine`, as previously discussed in #20.

Unfortunately, there is no action I can take to resolve it.

**Comment by shinyypig** [comment]
If you are using MacOS or Linux, yes.
