### ISSUE TITLE
增加语法高亮？

### ISSUE THREAD

**Issue by ivaquero** [shinyypig/matlab-in-vscode#44]
在mac上运行没有语法高亮，在源码里也没发现对应部分，希望增加语法高亮。

**Comment by shinyypig** [comment]
安装官方matlab插件就有语法高亮了。

**Comment by ivaquero** [comment]
是的，但官方的那个总是要求连接Matlab ，很烦而且还占内存，这个扩展如果有高亮，完全可以不用官方的那个。

**Comment by shinyypig** [comment]
<img width="890" alt="image" src="https://github.com/shinyypig/matlab-in-vscode/assets/30233673/0bbca113-f215-4c75-9f0d-4f9bf98abe3a">

修改设置即可。

**Comment by ivaquero** [comment]
我之前看到了，但尝试之后无效。

**Comment by ivaquero** [comment]
我真心希望这个扩展成为唯一的matlab扩展

**Comment by shinyypig** [comment]
那就没办法了，很可惜，我目前没有时间和精力去完成这一功能。

非常欢迎你或者其他有能力的开发者开发相关功能。

**Comment by ivaquero** [comment]
https://github.com/shinyypig/matlab-in-vscode/pull/45
