### ISSUE TITLE
Non UTF-8 chars are removed from path

### ISSUE THREAD

**Issue by Accelerox** [shinyypig/matlab-in-vscode#6]
First of all, using non UTF8 characters in paths is bad practice, however, I'm in a position where I cant change the paths since they are determined by my University. With that said...

Having a non UTF8 characters in the path won't work when pressing the "Run current matlab file" in vscode. However, running current cell works fine.

Pressing run file yields:

```
run('/Users/max/Library/CloudStorage/OneDrive-Linkpingsuniversitet/Sensor_Fusion_TSRT14/Lab2/test.m')
Error using run
/Users/max/Library/CloudStorage/OneDrive-Linkpingsuniversitet/Sensor_Fusion_TSRT14/Lab2/test.m not found.
````
The "ö" in the path has disappeared on closer inspection, real path is equal to
```
/Users/max/Library/CloudStorage/OneDrive-Linköpingsuniversitet/Sensor_Fusion_TSRT14/Lab2/test.m
```

**Comment by shinyypig** [comment]
What is the version of MATLAB and Python you are currently using?

I have tested running a .m file with a path containing non-UTF8 characters, and have found that everything worked fine with MATLAB 2023a and Python 3.9.

**Comment by Accelerox** [comment]
Sure thing! I conducted two more tests with different settings and got one of them to work.
The above test was done with the settings
- Matlab pybackend: No
- MacOS Ventura 13.3.1(1), 
- Matlab R2022b ARM Beta version 
- Python 3.10.9

 Second test displaying the same issue on Linux (I have sneeked in a Ö after Sensor Fusion Folder)
- Matlab pybackend: No
- Ubuntu 23.04
- Matlab R2023a x64
- Python 3.10.9

```
(base) max@ubuntu:TSRT14-Lab2 $ /usr/local/bin/matlab -nodesktop -nosplash

                                                        < M A T L A B (R) >
                                              Copyright 1984-2023 The MathWorks, Inc.
                                         R2023a Update 1 (9.14.0.2239454) 64-bit (glnxa64)
                                                           March 30, 2023

Warning: X does not support locale en_US.UTF-8
 
To get started, type doc.
For product information, visit www.mathworks.com.
 
f>> printf('Working directory: %s\n', pwd);
Working directory: /home/max/Nextcloud/Utbildning/Universitet/4_e aret/TSRT14 - Sensor FusionÖ/TSRT14-Lab2
>> run('/home/max/Nextcloud/Utbildning/Universitet/4_e aret/TSRT14 - Sensor Fusion/TSRT14-Lab2/test.m')
Error using run
/home/max/Nextcloud/Utbildning/Universitet/4_e aret/TSRT14 - Sensor Fusion/TSRT14-Lab2/test.m not found. 
>> 
```

Doing a test with Ubuntu and pybackend enabled (wiith a "ö" in path after "Sensor Fusion")
- Matlab pybackend: Yes
-  Other settings same as previous
```
python /home/max/.vscode/extensions/shinyypig.matlab-in-vscode-0.3.2/pybackend/matlab_engine.py --cmd="""fprintf('Working directory: %s\n', pwd);"""
(base) max@ubuntu:TSRT14-Lab2 $ python /home/max/.vscode/extensions/shinyypig.matlab-in-vscode-0.3.2/pybackend/matlab_engine.py --cmd="""fprintf('Working directory: %s\n', pwd);"""
---------------------------------------------------------
MATLAB Engine for Python is ready (terminate with 'quit')
---------------------------------------------------------
Working directory: /home/max/Nextcloud/Utbildning/Universitet/4_e aret/TSRT14 - Sensor Fusion/TSRT14-Lab2
>>> run('/home/max/Nextcloud/Utbildning/Universitet/4_e aret/TSRT14 - Sensor FusionÖ/TSRT14-Lab2/test.m')
z =
    10
>>> 
```
- success!
However, an interesting note on how the "Working directory" print doesn't include the Ö while the run path does!

**Comment by shinyypig** [comment]
It seems to be a issue with matlab.
```
(base) max@ubuntu:TSRT14-Lab2 $ /usr/local/bin/matlab -nodesktop -nosplash

                                                        < M A T L A B (R) >
                                              Copyright 1984-2023 The MathWorks, Inc.
                                         R2023a Update 1 (9.14.0.2239454) 64-bit (glnxa64)
                                                           March 30, 2023

Warning: X does not support locale en_US.UTF-8
```

Can files with non-UTF-8 characters in their paths be run directly from the Matlab command line?

**Comment by Accelerox** [comment]
Yeah, the command 
```
run('/home/max/Nextcloud/Utbildning/Universitet/4_e aret/TSRT14 - Sensor FusionÖ/TSRT14-Lab2/test.m')
``` 
with the Ö works fine from within the matlab command prompt.

Correct me if im'm wrong. butt since the extension is "building" the run command (without the ö) it should be the extension having problem with the char? As we can see from test 2: The run command is wrongly built, which gets generated from pressing the "run" button from within vscode. 
```
>>> run('/home/max/Nextcloud/Utbildning/Universitet/4_e aret/TSRT14 - Sensor Fusion/TSRT14-Lab2/test.m')
```
However, I agree that the error message regarding locale support is weird, however Mathworks says it should have no functionality changes https://www.mathworks.com/matlabcentral/answers/1925710-warning-x-does-not-support-locale-en_us-utf-8
