### ISSUE TITLE
Command to run a single line

### ISSUE THREAD

**Issue by fcdimitr** [shinyypig/matlab-in-vscode#9]
Thank you very much for this extension; it works perfectly!

Is adding one more command to run the current line in the file easy (and possibly automatically moving on to the following line)?

Thanks!

**Comment by shinyypig** [comment]
Thank you for your valuable suggestion. I have add this function in version 0.3.4.

You can press `shift+enter` to run the current line and move to next line (you can config whether to move next line in the settings).

Glad that you like this extension!

**Comment by fcdimitr** [comment]
Perfect, thank you very much! I just tried it, and it works like a charm!
Would it be easy to adjust it so that when a region is active (multiple lines selected), `shift+enter`  would run the whole region? Just wondering because I have been used to the `Julia` interface to run parts of a file. 😄 

Again, thank you very much!

**Comment by shinyypig** [comment]
It's relatively simple. Just making some minor modifications to the code can achieve it. Try upgrading to version 0.3.5.

**Comment by fcdimitr** [comment]
Wow, thank you for the speedy improvements!

I just noticed that when using `MATLAB` (not `Python`) executable, it prints the following in the command line:

```
fprintf( '\n *** (begin) %s ***\n\n', mfilename )

>> disp(evalc(char(sprintf("\n\nfprintf( '\n *** (begin) \n\n\n"))));
Error: Character vector is not terminated properly. 
>> variable_info;
```

It is likely an issue with the single/double quote. I am unsure if this was introduced with the latest updates or if the same problem existed before. It happens even when running a cell with `Cmd+enter`.

I don't remember the behavior when running cells with print commands, but I thought they worked perfectly fine before.

Again, thank you for all your work on this, it is a game-changer for MATLAB development!

**Comment by shinyypig** [comment]
It seems to be a mistake to use `evalc` to run multiple lines. Have reverted to the previous mode in 0.4.1.
Thank you again!

**Comment by fcdimitr** [comment]
With 0.4.1 I get the following:

```
fprintf( '\n *** (begin) %s ***\n\n', 'TEST' )
```

```
>> fprintf( '\n *** (begin) 
 fprintf( '\n *** (begin) 
          |
Error: Character vector is not terminated properly.
```

So now it does not use `evalc` but parsing the file has a similar issue. (I am using the cell-run command)

**Comment by fcdimitr** [comment]
I think the problem is at `%s`, maybe you consider every character starting with `$%` as a comment?

**Comment by shinyypig** [comment]
Yes, it is. I have compiled a new version. Maybe you can help me test it. Unzip the file and install it by clicking `Install from VSIX`.

[matlab-in-vscode-0.4.2.zip](https://github.com/shinyypig/matlab-in-vscode/files/11860192/matlab-in-vscode-0.4.2.zip)

<img width="633" alt="image" src="https://github.com/shinyypig/matlab-in-vscode/assets/30233673/d146523e-ce20-4667-885b-7484e3774ca0">

**Comment by fcdimitr** [comment]
It looks like everything works perfectly! You can publish v0.4.2

I observed a temporary CSV file created in the directory for showing the variables in the built-in VS code web viewer.

![Screen Shot 2023-06-25 at 12 32 29](https://github.com/shinyypig/matlab-in-vscode/assets/4839092/c1d9b51d-eb5b-4c07-a888-80480e004b74)

You may write in the README that this is temporary and can be safely deleted. Do you think this makes sense?

Other than that, I suggest you close this issue. Thank you!

**Comment by shinyypig** [comment]
Thanks again!

Actually, the CSV file is designed to be deleted immediately. But if something wrong happens, it could not be deleted. In this case, you can delete it yourself. 

Thank you for your remindation. I have added this statement to readme.
